{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.0",
    "title": "Booker API",
    "description": "Booker API for all routes",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "https://booker-back-end.herokuapp.com" }],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "User",
      "description": "User endpoints"
    },
    {
      "name": "Books",
      "description": "Books endpoints"
    },
    {
      "name": "Training",
      "description": "Training endpoints"
    }
  ],
  "paths": {
    "/api/user/registration": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "missing required name field or the field did not pass validation",
            "content": {}
          },
          "409": {
            "description": "User with this email is already registered",
            "content": {}
          }
        }
      }
    },

    "/api/user/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "parameters": [],
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "missing required name field or the field did not pass validation",
            "content": {}
          },

          "401": {
            "description": "Email or password is wrong",
            "content": {}
          }
        }
      }
    },

    "/api/user/logout": {
      "get": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful operation",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/user/verify/{verificationToken}": {
      "get": {
        "tags": ["Auth"],
        "summary": "Verify user email",
        "parameters": [
          {
            "in": "path",
            "name": "verificationToken",
            "type": "string",
            "example": "70c8de25-b20b-4a27-b63c-91686c99c9d3",
            "description": "verificationToken of user",
            "required": true
          }
        ],

        "responses": {
          "302": {
            "description": "Redirect to login route"
          },

          "404": {
            "description": "User not found",
            "content": {}
          }
        }
      }
    },

    "/api/user/verify": {
      "post": {
        "tags": ["Auth"],
        "summary": "resend verificationToken to email",
        "parameters": [],
        "requestBody": {
          "description": "Object for resend verificationToken",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostVerifyRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PostVerifyResponse"
                }
              }
            }
          },
          "400": {
            "description": "This mail is not registered or Verification has already been passed",
            "content": {}
          }
        }
      }
    },

    "/api/user/forgotPassword": {
      "patch": {
        "tags": ["Auth"],
        "summary": "Post newPassword",
        "parameters": [],
        "requestBody": {
          "description": "newPassword's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PatchForgotPasswordRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PatchForgotPasswordResponse"
                }
              }
            }
          },
          "400": {
            "description": "missing required name field or the field did not pass validation",
            "content": {}
          },

          "401": {
            "description": "This mail is not registered or Email not verify",
            "content": {}
          }
        }
      }
    },

    "/api/user/forgotPassword/{newPasswordToken}": {
      "get": {
        "tags": ["Auth"],
        "summary": "Confirm new password",
        "parameters": [
          {
            "in": "path",
            "name": "newPasswordToken",
            "type": "string",
            "example": "6fe48f15-6cbe-4275-9540-b8a04b3b264d",
            "description": "newPasswordToken",
            "required": true
          }
        ],

        "responses": {
          "302": {
            "description": "Redirect to login route"
          },

          "404": {
            "description": "User not found",
            "content": {}
          }
        }
      }
    },

    "/api/user/current": {
      "get": {
        "tags": ["User"],
        "summary": "Current User info",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentResponse"
                }
              }
            }
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/books": {
      "post": {
        "tags": ["Books"],
        "summary": "Add book",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Books's post object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostBookRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PostBookResponse"
                }
              }
            }
          },

          "400": {
            "description": "missing required fields or the field did not pass validation",
            "content": {}
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      },

      "get": {
        "tags": ["Books"],
        "summary": "Get books",
        "parameters": [],
        "security": [{ "Bearer": [] }],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetBooksResponse"
                }
              }
            }
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/books/{bookId}": {
      "get": {
        "tags": ["Books"],
        "summary": "Find book by id",
        "parameters": [
          {
            "in": "path",
            "name": "bookId",
            "type": "string",
            "example": "633430de05d976545f184b08",
            "description": "id of the book",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetBookByIdResponse"
                }
              }
            }
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      },
      "delete": {
        "tags": ["Books"],
        "summary": "Delete book by id",
        "parameters": [
          {
            "in": "path",
            "name": "bookId",
            "type": "string",
            "example": "633430de05d976545f184b08",
            "description": "id of the book",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DeleteBookByIdResponse"
                }
              }
            }
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/books/status/{bookId}": {
      "put": {
        "tags": ["Books"],
        "summary": "update status of the book",
        "parameters": [
          {
            "in": "path",
            "name": "bookId",
            "type": "string",
            "example": "633430de05d976545f184b08",
            "description": "id of the book",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "new status of the book",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutStatusRequest"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PutStatusResponse"
                }
              }
            }
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/books/resume/{bookId}": {
      "put": {
        "tags": ["Books"],
        "summary": "update resume of the book",
        "parameters": [
          {
            "in": "path",
            "name": "bookId",
            "example": "633430de05d976545f184b08",
            "type": "string",
            "description": "id of the book",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "new resume of the book",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutResumeRequest"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PutResumeResponse"
                }
              }
            }
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/books/edit/{bookId}": {
      "put": {
        "tags": ["Books"],
        "summary": "update title, author or other properties of the book",
        "parameters": [
          {
            "in": "path",
            "name": "bookId",
            "example": "633430de05d976545f184b08",
            "type": "string",
            "description": "id of the book",
            "required": true
          }
        ],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "new properties of the book",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PutEditRequest"
              }
            }
          }
        },

        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PutEditResponse"
                }
              }
            }
          },

          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      }
    },

    "/api/training": {
      "post": {
        "tags": ["Training"],
        "summary": "Add user training",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Training's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PostTrainingRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TrainingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Chosen books have already been read or training period should be greater than 1 day and must not exceed 31 days",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          },
          "403": {
            "description": "Training is in progress",
            "content": {}
          }
        }
      },

      "get": {
        "tags": ["Training"],
        "summary": "User training",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TrainingResponse"
                }
              }
            }
          },

          "404": {
            "description": "Not found",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          }
        }
      },

      "patch": {
        "tags": ["Training"],
        "summary": "Update user stats",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Stats's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PatchTrainingRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PatchTrainingResponse"
                }
              }
            }
          },
          "400": {
            "description": "Chosen books have already been read or training period should be greater than 1 day and must not exceed 31 days",
            "content": {}
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          },
          "403": {
            "description": "Training is completed!",
            "content": {}
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["name", "email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Mango"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },

      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "data": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Mango"
              },

              "password": {
                "type": "string",
                "description": "User's hashpassword",
                "example": "$2a$10$brs0hDVMGOWgv6D.qTD/vOhUbBL/NXWMPyNyervXeYeY0pRche.Hm"
              },

              "email": {
                "type": "string",
                "description": "User's email",
                "format": "email"
              },

              "token": {
                "type": null,
                "description": "User's token",
                "example": null
              },

              "verify": {
                "type": null,
                "description": "if users mail is verified",
                "example": null
              },

              "verificationToken": {
                "type": "string",
                "description": "token to get varification",
                "example": "90848095-2aa5-4930-b148-d2e273b3d534"
              },

              "newPassword": {
                "type": "string",
                "description": "new password if user dont know password",
                "example": ""
              },

              "newPasswordToken": {
                "type": "string",
                "description": "token to confirm new password",
                "example": ""
              },

              "_id": {
                "type": "string",
                "description": "User's id",
                "example": "6313700a788308a1f5ee225"
              }
            }
          }
        },

        "example": {
          "data": {
            "name": "Mango",
            "password": "$2b$10$hzBbMp/LXOdehW23fGBNT.v76O9AM5fepJGDdlaJgk8eSAMGiBaaG",
            "email": "user@example.com",
            "token": null,
            "verify": false,
            "verificationToken": "90848095-2aa5-4930-b148-d2e273b3d534",
            "newPassword": "",
            "newPasswordToken": "",
            "_id": "6339ed0a66fcaa338445957a"
          }
        }
      },

      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },

      "LoginResponse": {
        "type": "object",

        "properties": {
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "7c65b154-f218-4417-a0a8-b2609d9c0de4"
          },
          "name": {
            "type": "string",
            "description": "User's token",
            "example": "Mango"
          }
        },

        "example": {
          "token": "7c65b154-f218-4417-a0a8-b2609d9c0de4",
          "name": "Mango"
        }
      },

      "PatchForgotPasswordRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },

      "PatchForgotPasswordResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "succses",
            "example": "We have sent you a link to your email to confirm your new password."
          }
        },

        "example": {
          "message": "We have sent you a link to your email to confirm your new password."
        }
      },

      "CurrentResponse": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Mango"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        },

        "example": {
          "name": "Mango",
          "email": "user@example.com"
        }
      },

      "PostVerifyRequest": {
        "type": "object",
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        }
      },

      "PostVerifyResponse": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "succses",
            "example": "Verification email sent"
          }
        },

        "example": {
          "message": "Verification email sent"
        }
      },

      "PostBookRequest": {
        "type": "object",
        "required": ["title", "author", "pages"],
        "properties": {
          "title": {
            "type": "string",
            "description": "Book's title",
            "example": "The Art of War"
          },
          "author": {
            "type": "string",
            "description": "Book's author",
            "example": "Sun Tzu"
          },
          "year": {
            "type": "integer",
            "description": "year of publication",
            "example": 1974
          },
          "pages": {
            "type": "integer",
            "description": "pages in book",
            "example": 100
          }
        }
      },

      "PostBookResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "succses",
            "example": "Succses"
          },
          "code": {
            "type": "integer",
            "description": "code",
            "example": 200
          },
          "payload": {
            "type": "object",
            "properties": {
              "book": {
                "type": "object",

                "properties": {
                  "title": {
                    "type": "string",
                    "description": "Book's title",
                    "example": "The Art of War"
                  },
                  "author": {
                    "type": "string",
                    "description": "Book's author",
                    "example": "Sun Tzu"
                  },
                  "year": {
                    "type": "integer",
                    "description": "year of publication",
                    "example": 1974
                  },
                  "pages": {
                    "type": "integer",
                    "description": "pages in book",
                    "example": 100
                  },
                  "status": {
                    "type": "string",
                    "description": "curreny status of the book",
                    "example": "toRead"
                  },
                  "rating": {
                    "type": "integer",
                    "description": "rating of the book",
                    "example": 0
                  },
                  "owner": {
                    "type": "string",
                    "description": "owner's (user's) id",
                    "example": "6331e0bd7d50cafaf02cf8c8"
                  },
                  "_id": {
                    "type": "string",
                    "description": "id of the book",
                    "example": "633b1aae155b3020faa54d9e"
                  }
                }
              }
            }
          }
        },

        "example": {
          "status": "Success",
          "code": 200,
          "payload": {
            "book": {
              "title": "The Art of War",
              "author": "Sun Tzu",
              "year": 1974,
              "pages": 100,
              "status": "toRead",
              "rating": 0,
              "owner": "6337283619ffb3c7da56c9a4",
              "_id": "633b1aae155b3020faa54d9e"
            }
          }
        }
      },

      "GetBooksResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "succses",
            "example": "Succses"
          },
          "code": {
            "type": "integer",
            "description": "code",
            "example": 200
          },
          "payload": {
            "type": "object",
            "properties": {
              "books": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "title": {
                      "type": "string",
                      "description": "Book's title",
                      "example": "The Art of War"
                    },
                    "author": {
                      "type": "string",
                      "description": "Book's author",
                      "example": "Sun Tzu"
                    },
                    "year": {
                      "type": "integer",
                      "description": "year of publication",
                      "example": 1974
                    },
                    "pages": {
                      "type": "integer",
                      "description": "pages in book",
                      "example": 100
                    },
                    "status": {
                      "type": "string",
                      "description": "curreny status of the book",
                      "example": "toRead"
                    },
                    "rating": {
                      "type": "integer",
                      "description": "rating of the book",
                      "example": 0
                    },
                    "owner": {
                      "type": "string",
                      "description": "owner's (user's) id",
                      "example": "6331e0bd7d50cafaf02cf8c8"
                    },
                    "_id": {
                      "type": "string",
                      "description": "id of the book",
                      "example": "633b1aae155b3020faa54d9e"
                    }
                  }
                }
              }
            }
          }
        },

        "example": {
          "status": "Succses",
          "code": 200,
          "payload": {
            "books": [
              {
                "_id": "633430de05d976545f184b08",
                "title": "The Art of War",
                "author": "Sun Tzu",
                "year": 1974,
                "pages": 100,
                "rating": 0,
                "status": "toRead",
                "owner": "6331e0bd7d50cafaf02cf8c8"
              },
              {
                "_id": "6331fa40c8e0d7f99f187435",
                "title": "1984",
                "author": "George Orwell",
                "year": 1949,
                "pages": 100,
                "rating": 0,
                "status": "toRead",
                "owner": "6331e0bd7d50cafaf02cf8c8"
              }
            ]
          }
        }
      },

      "GetBookByIdResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "succses",
            "example": "Succses"
          },
          "code": {
            "type": "integer",
            "description": "code",
            "example": 200
          },
          "payload": {
            "type": "object",
            "properties": {
              "book": {
                "properties": {
                  "_id": {
                    "type": "string",
                    "description": "id of the book",
                    "example": "633430de05d976545f184b08"
                  },
                  "title": {
                    "type": "string",
                    "description": "Book's title",
                    "example": "The Art of War"
                  },
                  "author": {
                    "type": "string",
                    "description": "Book's author",
                    "example": "Sun Tzu"
                  },
                  "year": {
                    "type": "integer",
                    "description": "year of publication",
                    "example": 1974
                  },
                  "pages": {
                    "type": "integer",
                    "description": "pages in book",
                    "example": 100
                  },
                  "rating": {
                    "type": "integer",
                    "description": "rating of the book",
                    "example": 0
                  },
                  "status": {
                    "type": "string",
                    "description": "curreny status of the book",
                    "example": "toRead"
                  },
                  "owner": {
                    "type": "string",
                    "description": "owner's (user's) id",
                    "example": "6331e0bd7d50cafaf02cf8c8"
                  }
                }
              }
            }
          }
        },

        "example": {
          "status": "Succses",
          "code": 200,
          "payload": {
            "book": {
              "_id": "633430de05d976545f184b08",
              "title": "The Art of War",
              "author": "Sun Tzu",
              "year": 1974,
              "pages": 100,
              "rating": 0,
              "status": "toRead",
              "owner": "6331e0bd7d50cafaf02cf8c8"
            }
          }
        }
      },

      "DeleteBookByIdResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "succses",
            "example": "Succses"
          }
        },

        "example": {
          "status": "Succses"
        }
      },

      "PutStatusResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "succses",
            "example": "Succses"
          }
        },

        "example": {
          "status": "Succses"
        }
      },

      "PutStatusRequest": {
        "type": "object",
        "required": ["status"],
        "properties": {
          "status": {
            "type": "string",
            "description": "new status of the book",
            "example": "reading"
          }
        }
      },

      "PutResumeResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "succses",
            "example": "Succses"
          }
        },

        "example": {
          "status": "Succses"
        }
      },

      "PutResumeRequest": {
        "type": "object",
        "required": ["status"],
        "properties": {
          "resume": {
            "type": "string",
            "description": "new resume of the book",
            "example": "exciting book, that blow my mind"
          },

          "rating": {
            "type": "integer",
            "description": "new rating of the book",
            "example": 4
          }
        }
      },

      "PutEditRequest": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Book's title",
            "example": "The Art of War"
          },
          "author": {
            "type": "string",
            "description": "Book's author",
            "example": "Sun Tzu"
          },
          "year": {
            "type": "integer",
            "description": "year of publication",
            "example": 1974
          },
          "pages": {
            "type": "integer",
            "description": "pages in book",
            "example": 100
          }
        }
      },

      "PutEditResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "description": "succses",
            "example": "Succses"
          },
          "code": {
            "type": "integer",
            "description": "code",
            "example": 200
          },
          "payload": {
            "type": "object",
            "properties": {
              "book": {
                "properties": {
                  "title": {
                    "type": "string",
                    "description": "Book's title",
                    "example": "The Art of War"
                  },
                  "author": {
                    "type": "string",
                    "description": "Book's author",
                    "example": "Sun Tzu"
                  },
                  "year": {
                    "type": "integer",
                    "description": "year of publication",
                    "example": 1974
                  },
                  "pages": {
                    "type": "integer",
                    "description": "pages in book",
                    "example": 100
                  }
                }
              }
            }
          }
        },

        "example": {
          "status": "Succses",
          "code": 200,
          "payload": {
            "book": {
              "_id": "633430de05d976545f184b08",
              "title": "The Art of War",
              "author": "Sun Tzu",
              "year": 1974,
              "pages": 100,
              "rating": 0,
              "status": "toRead",
              "owner": "6331e0bd7d50cafaf02cf8c8"
            }
          }
        }
      },

      "PostTrainingRequest": {
        "type": "object",
        "required": ["startDate", "finishDate", "books"],
        "properties": {
          "startDate": {
            "type": "date-time",
            "description": "when the training start's",
            "example": "2022-10-21T17:32:28Z"
          },
          "finishDate": {
            "type": "date-time",
            "description": "when the training end's",
            "example": "2022-10-27T17:32:28Z"
          },
          "books": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "id of the book",
                  "example": "633430de05d976545f184b08"
                }
              }
            }
          }
        }
      },

      "TrainingResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "id of the training",
            "example": "63333edbe0608187191dc8f4"
          },
          "startDate": {
            "type": "date-time",
            "description": "when the training start's",
            "example": "2022-10-21T17:32:28Z"
          },
          "finishDate": {
            "type": "date-time",
            "description": "when the training end's",
            "example": "2022-10-27T17:32:28Z"
          },
          "books": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "id of the book",
                  "example": "633430de05d976545f184b08"
                },
                "pages": {
                  "type": "intager",
                  "description": "number of pages",
                  "example": 100
                },
                "status": {
                  "type": "string",
                  "description": "status of the book",
                  "example": "reading"
                }
              }
            }
          },

          "completed": {
            "type": "boolean",
            "description": "if the book is completed",
            "example": false
          },
          "owner": {
            "type": "string",
            "description": "id of the user",
            "example": "6331e0bd7d50cafaf02cf8c8"
          },
          "results": {
            "type": "array",
            "description": "array of results",
            "example": []
          }
        },

        "example": {
          "_id": "63333edbe0608187191dc8f4",
          "startDate": "2022-09-28T17:32:28.000Z",
          "finishDate": "2022-09-30T17:32:28.000Z",
          "books": [
            {
              "_id": "633430de05d976545f184b08",
              "pages": 100,
              "status": "reading"
            }
          ],
          "completed": false,
          "owner": "6331e0bd7d50cafaf02cf8c8",
          "results": []
        }
      },

      "PatchTrainingRequest": {
        "type": "object",
        "properties": {
          "date": {
            "type": "date-time",
            "description": "when the pages was read",
            "example": "2022-10-21T17:32:28Z"
          },
          "pages": {
            "type": "integer",
            "description": "number of pages",
            "example": 20
          }
        }
      },

      "PatchTrainingResponse": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "description": "id of the training",
            "example": "63333edbe0608187191dc8f4"
          },
          "startDate": {
            "type": "date-time",
            "description": "when the training start's",
            "example": "2022-10-21T17:32:28Z"
          },
          "finishDate": {
            "type": "date-time",
            "description": "when the training end's",
            "example": "2022-10-27T17:32:28Z"
          },

          "books": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "ObjectId",
                  "description": "id of the book",
                  "example": "ObjectId(633070c1ba4415bbf6e640a0)"
                },
                "status": {
                  "type": "string",
                  "description": "status of the book",
                  "example": "reading"
                }
              }
            }
          },

          "completed": {
            "type": "boolean",
            "description": "if the book is completed",
            "example": false
          },
          "owner": {
            "type": "string",
            "description": "id of the user",
            "example": "6331e0bd7d50cafaf02cf8c8"
          },
          "results": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "id of the stats",
                  "example": "633070c1ba4415bbf6e640a0"
                },
                "date": {
                  "type": "date-time",
                  "description": "when the pages was read",
                  "example": "2022-10-21T17:32:28Z"
                },
                "pages": {
                  "type": "integer",
                  "description": "number of pages",
                  "example": 20
                }
              }
            }
          }
        },

        "example": {
          "_id": "63333edbe0608187191dc8f4",
          "startDate": "2022-09-26T10:32:28.000Z",
          "finishDate": "2022-09-30T17:32:28.000Z",
          "books": [
            {
              "_id": "6331fa40c8e0d7f99f18745a",
              "pages": 100,
              "status": "reading"
            }
          ],
          "completed": false,
          "owner": "6331e0bd7d50cafaf02cf8c8",
          "results": [
            {
              "date": "2022-09-27T11:32:28.000Z",
              "pages": 20,
              "_id": "633429f4b05410a6b33fcc1d"
            }
          ]
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
